wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.24
    framework: huggingface
    huggingface_version: 2.4.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      2:
      - 1
      - 3
      - 5
      - 11
      3:
      - 1
      4: 3.7.3
      5: 0.10.24
      6: 2.4.1
      8:
      - 5
